# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
debug: true
title: Don's Blog
email: kos5667@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#favicon: "./favicons.png" # the favicon for your site
asset_url: "/assets"

#twitter_username: jekyllrb
#github_username:  kos5667
# https://fontawesome.com/v4/
social:
  - {icon: 'github',     link: 'https://github.com/kos5667'}
  - {icon: 'linkedin',   link: 'https://www.linkedin.com/in/don-jh1025/'}
  - {icon: 'instagram',  link: 'https://www.instagram.com/don.jh93/'}

# Build settings
#theme: jekyll-theme-yat
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Comments
# utterances - https://utteranc.es/?installation_id=49450710&setup_action=install
#utterances:
#  repo: kos5667/kos5667.github.io
#  issue_term: url
#  label: Comment
#  theme: preferred-color-scheme

# Giscus(https://giscus.app/ko)
giscus:
  repo: kos5667/kos5667.github.io
  repo_id: R_kgDOLpTseg
  category: Q&A
  category_id: DIC_kwDOLpTses4CeltF
  mapping: url
  strict: 0 # 엄격한 제목 일치 사용(0: N, 1: Y)
  reactions_enabled: 1 # 메인 포스트에 반응 남기기(0: N, 1: Y)
  metadata: 0 # Discussion 메타데이터 보내기(0: N, 1: Y)
  input_position: top # 댓글 위에 댓글 상자 배치(top, bottom)
  theme: preferred_color_scheme
  lang: ko

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Search Console
google-site-verification: UfQe4a2Al1OOfPusFjfdzFl2hSqDIYsk3e8Z3Q2-JKc
